import { createAction } from "../../helpers";

export const userconstants = {
  ...createAction("USER"),
  GET_BY_ID_REQUEST: "USER_GET_BY_ID_REQUEST",
  GET_BY_ID_SUCCESS: "USER_GET_BY_ID_SUCCESS",
  GET_BY_ID_ERROR: "USER_GET_BY_ID_ERROR",
  UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  UPDATE_ERROR: "USER_UPDATE_ERROR",
  DELETE_REQUEST: "USER_DELETE_REQUEST",
  DELETE_SUCCESS: "USER_DELETE_SUCCESS",
  DELETE_ERROR: "USER_DELETE_ERROR",
  CREATE_REQUEST: "USER_CREATE_REQUEST",
  CREATE_SUCCESS: "USER_CREATE_SUCCESS",
  CREATE_ERROR: "USER_CREATE_ERROR",
  SET_FILTERED_DATA: "USER_SET_FILTERED_DATA",
};